Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 151, in extract
  File "Extract.py", line 4, in main
  File "openpyxl\reader\excel.py", line 346, in load_workbook
  File "openpyxl\reader\excel.py", line 123, in __init__
  File "openpyxl\reader\excel.py", line 93, in _validate_archive
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
----------Above 2024-10-05 09:53:50----------

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 151, in extract
  File "Extract.py", line 4, in main
  File "openpyxl\reader\excel.py", line 346, in load_workbook
  File "openpyxl\reader\excel.py", line 123, in __init__
  File "openpyxl\reader\excel.py", line 93, in _validate_archive
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
----------Above 2024-10-05 10:17:55----------

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 151, in extract
  File "Extract.py", line 4, in main
  File "openpyxl\reader\excel.py", line 346, in load_workbook
  File "openpyxl\reader\excel.py", line 123, in __init__
  File "openpyxl\reader\excel.py", line 93, in _validate_archive
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
----------Above 2024-10-05 18:27:39----------

